- hosts: all
  vars:
    sites:
      - name: foo.com
        dir: /var/www/foo_com
      - name: bar.com
        dir: /var/www/bar_com
      - name: foobar.com
        dir: /var/www/foobar_com

  tasks:
    - apt: name=nginx
    - template:
        src: templates/nginx.conf
        dest: /etc/nginx/
    - file: name={{item.dir}} state=directory
      with_items: "{{sites}}"
    - synchronize:
        src: ../www/{{item.dir|basename}}/
        dest: "{{item.dir}}/"
        delete: yes
      with_items: "{{sites}}"
    - template:
        src: templates/nginx_sites.conf
        dest: /etc/nginx/sites-enabled/
    - service: name=nginx state=reloaded
