- hosts: all
  user: root
  tasks:
  - block:
    - name: install packages update_cache=yes cache_valid_time=86400
      apt: name={{item}}
      with_items: [ntp, nginx, git]
    tags: packages
  - name: prepare nginx configs for site
    copy:
      src: files/nginx_site.conf
      dest: /etc/nginx/sites-enabled/
    notify: restart nginx
    tags: configs

  - include: deploy-site.yml
    tags: deploy

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
